### ISSUE TITLE
서버 시작시 에러

### ISSUE THREAD

**Issue by keonkim** [Hanul/HanulWiki#1]
![error](https://cloud.githubusercontent.com/assets/10793962/8464038/548cf1ce-207a-11e5-979a-264acf8cb385.png)

사양:
컴퓨터 windows 8 x64
nodeJS 최신 UPPPERCASE.io 최신
dependency 모두 설치

이제 막 설치하고 실험해보려던 찰나 버그가 납니다.
힝 왜 안될까요 ㅠㅠ

**Comment by Hanul** [comment]
아마도 릴리즈 버전 넘버링 때문에 착오가 있는것 같습니다.
다운받은 버젼은 1.4인것 같네요.
[UPPERCASE.IO 설치하기](https://github.com/Hanul/UPPERCASE.IO/blob/master/DOC/KR/INSTALL.md) 문서를 참고해주세요.
헷갈리지 않게 릴리즈에 git 관련 내용을 추가하였습니다.
감사합니다. :)
