### ISSUE TITLE
기능 건의

### ISSUE THREAD

**Issue by MPMaker** [Hanul/HanulWiki#2]
- 수정& 삭제불가 항목 지정(어드민은 수정 가능)
특정 ip 에게만 수정 가능하게 열어 줄수 있으면 더 좋을것 같습니다.

- 변경내역 타임라인 문제
글 작성 로그만 남고 수정 로그는 남지 않습니다.

- 게시글 재생성시 조회수 리셋 문제

-  . 등의 url 에 영향을 주는 문자 사용한 항목 관련 문제...

- 자동 링크의 영향이 큼에 따른 외자 항목 막을수 있는 기능 추가

- ip 밴이 서버 재시작하면 리셋되므로 db 에 저장하게

- 관리자나 사용자를 계정 등으로 개별 관리 가능하게

**Comment by Hanul** [comment]
- 수정& 삭제불가 항목 지정 -> 관리자만 수정 가능하게 하였습니다.

- 변경내역 타임라인 문제 -> UPPERCASE의 버그입니다. 처리하였습니다.

- 게시글 재생성시 조회수 리셋 문제 -> 삭제 했다가 다시 쓰는거니 어쩔수가 없습니다.

-  . 등의 url 에 영향을 주는 문자 사용한 항목 관련 문제... -> 항목을 제한하는것으로 대신하겠습니다.

- 자동 링크의 영향이 큼에 따른 외자 항목 막을수 있는 기능 추가 -> minTagLength 설정으로 추가

- ip 밴이 서버 재시작하면 리셋되므로 db 에 저장하게 -> 기능 추가하였습니다.

- 관리자나 사용자를 계정 등으로 개별 관리 가능하게 -> 시간이 많이걸려 우선은 패스합니다.
