### ISSUE TITLE
기능 건의

### ISSUE THREAD

**Issue by MPMaker** [Hanul/HanulWiki#3]
- 수정불가 항목 지정(어드민은 수정 가능)
특정 ip 에게만 수정 가능하게 열어 줄수 있으면 더 좋을것 같습니다.
그리고 수정불가 항목도 삭제는 아무나 가능한 문제가 있습니다.

- 변경내역 타임라인 문제
글 작성 로그만 남고 수정 로그는 남지 않습니다.

- 게시글 재생성시 조회수 리셋 문제

- 항목 삭제한 유저도 ip 기록하도록

-  . # 등의 url 에 영향을 주는 문자 사용한 항목 관련 문제...

- 자동 링크의 영향이 큼에 따른 외자 항목 막을수 있는 기능 추가

- ip 밴이 서버 재시작하면 리셋되므로 db 에 저장하게

- 관리자나 사용자를 계정 등으로 개별 관리 가능하게

- 자동링크가 경우에 따라 작동하지 않는 문제

**Comment by Hanul** [comment]
- 수정불가 항목 지정 - 관리자만 가능하도록 하였습니다.

- 변경내역 타임라인 문제 - 처리하였습니다.

- 게시글 재생성시 조회수 리셋 문제 - 처리하였습니다.

- 항목 삭제한 유저도 ip 기록하도록 - 처리하였습니다.

-  . # 등의 url 에 영향을 주는 문자 사용한 항목 관련 문제... - 처리하였습니다.

- 자동 링크의 영향이 큼에 따른 외자 항목 막을수 있는 기능 추가 - 추가하였습니다.

- ip 밴이 서버 재시작하면 리셋되므로 db 에 저장하게 - 추가하였습니다.

- 관리자나 사용자를 계정 등으로 개별 관리 가능하게 - 이건 힘이 듭니다.

- 자동링크가 경우에 따라 작동하지 않는 문제 - 처리하였습니다.
